### ISSUE TITLE
PyDP4: "no jobs to run"

### ISSUE THREAD

**Issue by cfares** [Goodman-lab/DP5#55]
I would like to use the new tool PyDP4.py to test my NMR data against a number of diastereomer to see if DP4 can help me find to the correct one. I am using it for the first time, so my problem is probably obvious.

I believe I have all of the python requirements correctly installed.
I have access to NWchem-7 and I have a single macromodel+maestro/schrodinger license.

I have generated my candidate diastereomers by hand (diastXX.sdf) and generated conformer ensembles with macromodel (diast-ensXX.sdf). In the workflow, I would in principle need at a minimum two more steps "-w ns" (n=DFT NMR calculation, s=calculate DP4 statistics).

For testing locally from the command prompt, I give the command:
python /hsnfs/software/DP5/PyDP4.py -w ns -s chloroform -d n diast-ensRR diast-ensRS nmrdata
but I get this output after a few seconds:

==========================
PyDP4 script,
integrating Tinker/MacroModel,
Gaussian/NWChem and DP4
v1.0

Copyright (c) 2015-2019 Kristaps Ermanis, Alexander Howarth, Jonathan M. Goodman
Distributed under MIT license
==========================

Settings read from settings.cfg:
  SCHRODINGER: /opt/schrodinger2020-4/
['diast-ensRR', 'diast-ensRS']
nmrdata
NMR_path
/hsnfs/users/fares/MFA-scaB/DP5/nmrdata
Current working directory: /hsnfs/users/fares/MFA-scaB/DP5
Initial input files: ['diast-ensRR', 'diast-ensRS']
NMR file: [PosixPath('/hsnfs/users/fares/MFA-scaB/DP5/nmrdata')]
Workflow: ns
Generated input files: ['diast-ensRR', 'diast-ensRS']

Assuming all computations are done? ...  False
Using preexisting DFT data? ...  False
No conformational search was requested. Skipping...

Setting up NMR calculations...

Running NMR calculations...

Running NWChem DFT NMR calculations locally...
[]
[]
There were no jobs to run.

Reading data from the output files...
NWChem.py, ReadShieldings: No NMR DFT output files found, NMR data could not be read. Quitting.

What am I doing incorrectly?

**Comment by HowarthA** [comment]
I'm closing this thread as We have chatted over email, if you run in to any more problems pls open a new thread :).
