### ISSUE TITLE
Problem while running Tinker

### ISSUE THREAD

**Issue by flatstik** [Goodman-lab/DP5#57]
PyDP4.py -f mmff -w gnomesw -m t -s b3lyp --InChI Inchis.inchi experimental_nmr_files

```
Setting up Tinker files...
Tinker input for InChI_Mol_0_0 prepared.

Running Tinker...
/appl/soft/chem/tinker/bin/scan InChI_Mol_0_0 /appl/soft/chem/tinker/params/mmff.prm 0 10 20 0.00001 | tee ./InChI_Mol_0_0.tout
Tinker job 1 of 1 completed.
InChI_Mol_0_0 is matching conformational search output for InChI_Mol_0_0
Reading InChI_Mol_0_0
Tinker output InChI_Mol_0_0 is corrupted, aborting.

```

The /appl/soft/chem/tinker/bin/scan InChI_Mol_0_0 /appl/soft/chem/tinker/params/mmff.prm 0 10 20 0.00001 | tee ./InChI_Mol_0_0.tout gives following

```
 INITROT  --  Rotation about     6     7 occurs more than once in Z-matrix

 Tinker is Unable to Continue; Terminating the Current Calculation
```

**Comment by flatstik** [comment]
The problem was in the Inchi format. After I switched to --Smiles, it worked

**Comment by flatstik** [comment]
Additional: 

Reading experimental NMR data...
[PosixPath('experimental_nmr_files/dada/1/Proton')]
Processing Proton Spectrum
minimisation time = 0.3785014748573303 mins
     number of protons = 13
     number of labile protons = 0
the best fit number of protons is 14
/scratch/project_2003067/DP5/DP5/Proton_processing.py:1563: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  whdel = np.where(picked_peaks == peaks_to_remove)
/scratch/project_2003067/DP5/DP5_env/lib/python3.9/site-packages/numpy/lib/function_base.py:4454: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asarray(arr)

Assigning proton spectrum...

Plotting proton spectrum...

Calculating DP5 probabilities...
[[[]]]
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/scratch/project_2003067/DP5/DP5_env/lib/python3.9/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/scratch/project_2003067/DP5/DP5/DP5.py", line 81, in kde_probfunction
    scaled_shifts = ScaleNMR(conf_shifts, dp5Data.Cexp[iso])
  File "/scratch/project_2003067/DP5/DP5/DP5.py", line 317, in ScaleNMR
    slope, intercept, r_value, p_value, std_err = stats.linregress(expShifts,
  File "/scratch/project_2003067/DP5/DP5_env/lib/python3.9/site-packages/scipy/stats/_stats_mstats_common.py", line 146, in linregress
    raise ValueError("Inputs must not be empty.")
ValueError: Inputs must not be empty.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/project_2003067/DP5/DP5/PyDP4.py", line 835, in <module>
    main(settings)
  File "/scratch/project_2003067/DP5/DP5/PyDP4.py", line 493, in main
    DP5data = DP5.kde_probs(Isomers, DP5data, 0.025)
  File "/scratch/project_2003067/DP5/DP5/DP5.py", line 136, in kde_probs
    dp5Data.ScaledAtomProbs[iso][ind1] = res[ind1].get()
  File "/scratch/project_2003067/DP5/DP5_env/lib/python3.9/site-packages/multiprocess/pool.py", line 771, in get
    raise self._value
ValueError: Inputs must not be empty.

**Comment by flatstik** [comment]
I cloned the package again and now I get following for PyDP4.py -f mmff -w gnomesw -m t -s b3lyp --Smiles smiles.list experimental_nmr_files

```
Running Gaussian DFT geometry optimizations locally...
/appl/soft/chem/gaussian/G16RevC.01_new/g16/g16 < Smiles_Mol_0_0ginp001.com > Smiles_Mol_0_0ginp001.out
Traceback (most recent call last):
  File "/scratch/project_2003067/DP5/DP5/PyDP4.py", line 835, in <module>
    main(settings)
  File "/scratch/project_2003067/DP5/DP5/PyDP4.py", line 317, in main
    Isomers = DFT.RunOptCalcs(Isomers, settings)
  File "/scratch/project_2003067/DP5/DP5/Gaussian.py", line 254, in RunOptCalcs
    Completed = RunCalcs(GausJobs, settings)
  File "/scratch/project_2003067/DP5/DP5/Gaussian.py", line 308, in RunCalcs
    outp = subprocess.check_output(GausPrefix + " < "  + f + ' > ' + f[:-3] + 'out', shell=True)
  File "/scratch/project_2003067/DP5/DP5_env/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/scratch/project_2003067/DP5/DP5_env/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/appl/soft/chem/gaussian/G16RevC.01_new/g16/g16 < Smiles_Mol_0_0ginp001.com > Smiles_Mol_0_0ginp001.out' returned non-zero exit status 1.
```
Which is understandable, because only these files are generated:

Smiles_Mol_0_0.arc
Smiles_Mol_0_0.key
Smiles_Mol_0_0.sdf
Smiles_Mol_0_0.tout
Smiles_Mol_0_0.xyz
Smiles_Mol_0_.sdf

**Comment by HowarthA** [comment]
I shall try to debug the first issue, this might be easier if you could send me your input files, the problem doesn't look to large. As for the error when you rerun the code, the first time you run the code DP5 makes an output file to store everything so its faster if you run it again. Because the calculation didn't finish properly DP5 looks for this file and doesn't find it. Delete the "dp5" folder to remove this problem.

**Comment by HowarthA** [comment]
for the second issue, does the program make an "opt" folder in your output location?

**Comment by flatstik** [comment]
> I shall try to debug the first issue, this might be easier if you could send me your input files, the problem doesn't look to large. As for the error when you rerun the code, the first time you run the code DP5 makes an output file to store everything so its faster if you run it again. Because the calculation didn't finish properly DP5 looks for this file and doesn't find it. Delete the "dp5" folder to remove this problem.

I removed everything, still the same issue for "PyDP4.py -f mmff -w gnomesw -m t -s b3lyp --Smiles smiles.list experimental_nmr_files_path_here"

[examples.tar.gz](https://github.com/Goodman-lab/DP5/files/7527779/examples.tar.gz)

**Comment by HowarthA** [comment]
hmm, interesting thank you. I'll finally have a look at this now.

**Comment by flatstik** [comment]
> hmm, interesting thank you. I'll finally have a look at this now, sorry its taken a while.

Ah, there's problem with the smiles.list.. I accidentally tarred everything in that. but the contents of it should be 
```
NCCc1ccccc1
CC1NCCc2ccccc12
```

**Comment by flatstik** [comment]
Interestingly, if I run it without "-s b3lyp" It can find the files and runs normally

**Comment by HowarthA** [comment]
the -s command is to specify the solvent, like "-s chloroform" run PyDP4.py -h for more help with the input switches. I haven't tested this fully, but I have a feeling the issue is with how the NMR files are arranged. The NMR folder should be arranged as below and the proton and carbon folders should be named this way. 

-NMRfolder
          - \Carbon
                  -raw/loose files
          - \Proton
                  -raw/loose files

I have done this in this example

[DP5_example.zip](https://github.com/Goodman-lab/DP5/files/7527985/DP5_example.zip)
.

**Comment by flatstik** [comment]
Yes, I wanted to use DMSO as the solvent.
Anyway, now that I ran it without solvent, I get this:

```
Converting DFT data to NMR shifts...
WARNING: NMR shift calculation currently ignores the instruction to exclude atoms from analysis
C shifts for isomer 0: 
48.942, 43.971, 146.412, 134.130, 132.063, 130.407, 133.050, 133.122
H shifts for isomer 0: 
0.349, -0.030, 2.872, 2.921, 2.654, 2.825, 7.357, 7.398, 7.349, 7.455, 7.299
C shifts for isomer 1: 
25.299, 55.601, 40.952, 32.224, 140.260, 133.844, 130.101, 130.040, 131.379, 147.076
H shifts for isomer 1: 
1.275, 1.445, 1.563, 4.060, 0.759, 3.033, 3.215, 2.674, 2.576, 7.154, 7.23```
2, 7.240, 7.105

Reading experimental NMR data...
[PosixPath('experimental_nmr_files/Proton/format.temp')]
Loading NMR data from [PosixPath('experimental_nmr_files/Proton/format.temp')]
['EDIT_PAR COMMAND FILE']
Traceback (most recent call last):
  File "/scratch/project_2003067/DP5/DP5/PyDP4.py", line 835, in <module>
    main(settings)
  File "/scratch/project_2003067/DP5/DP5/PyDP4.py", line 397, in main
    NMRData = NMR.NMRData(settings)
  File "/scratch/project_2003067/DP5/DP5/NMR.py", line 93, in __init__
    self.ExpNMRFromDesc()
  File "/scratch/project_2003067/DP5/DP5/NMR.py", line 125, in ExpNMRFromDesc
    self.Clabels, self.Cshifts = self.ParseExp(Cexp)
  File "/scratch/project_2003067/DP5/DP5/NMR.py", line 150, in ParseExp
    expShifts = [float(x) for x in ShiftData]
  File "/scratch/project_2003067/DP5/DP5/NMR.py", line 150, in <listcomp>
    expShifts = [float(x) for x in ShiftData]
ValueError: could not convert string to float: 'EDIT_PAR COMMAND FILE'
```

**Comment by flatstik** [comment]
> I have done this in this example
> 
> [DP5_example.zip](https://github.com/Goodman-lab/DP5/files/7527985/DP5_example.zip) .

I tried to run the example as before. It yielded this error:

```
Converting DFT data to NMR shifts...
WARNING: NMR shift calculation currently ignores the instruction to exclude atoms from analysis
C shifts for isomer 0: 
26.186, 53.213, 39.815, 32.288, 140.702, 133.260, 130.494, 129.559, 131.790, 145.168
H shifts for isomer 0: 
1.888, 0.796, 1.403, 4.349, 0.475, 2.842, 3.340, 2.606, 3.086, 7.238, 7.238, 7.236, 7.136

Reading experimental NMR data...
[PosixPath('huh/DP5_example/NMR_folder/Proton/Proton')]
Processing Proton Spectrum
minimisation time = 0.23923718134562175 mins
     number of protons = 13
==============================
*** Open Babel Error  in ReadFile
  Cannot read from Smiles_Mol_0_0
     number of labile protons = 0
the best fit number of protons is 14
/scratch/project_2003067/DP5/DP5/Proton_processing.py:1563: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  whdel = np.where(picked_peaks == peaks_to_remove)
/scratch/project_2003067/DP5/DP5_env/lib/python3.9/site-packages/numpy/lib/function_base.py:4454: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asarray(arr)

Assigning proton spectrum...

Plotting proton spectrum...
Multiple structures required for DP4 probability calculations...

PyDP4 process completed successfully.
workflow gmns
Traceback (most recent call last):
  File "/scratch/project_2003067/DP5/DP5/PyDP4.py", line 835, in <module>
    main(settings)
  File "/scratch/project_2003067/DP5/DP5/PyDP4.py", line 536, in main
    return NMRData, Isomers, settings, DP4data, DP5data
UnboundLocalError: local variable 'DP4data' referenced before assignment
```

**Comment by HowarthA** [comment]
This is really strange, its clearly very nearly there. Could you send me a copy of the example with the completed calculations? This will make it quicker to debug

**Comment by flatstik** [comment]
> This is really strange, its clearly very nearly there. Could you send me a copy of the example with the completed calculations? This will make it quicker to debug

You can download the example.tar.gz at https://mega.nz/file/7U92FCLT#5lCzql1e2rfkIIIQKjedhEbasjzfqZbUeukm1Z0qH9Q

**Comment by HowarthA** [comment]
I should have noticed this before, this is not a bug in the software.  As stated in the paper, DP5 runs with carbon data only. There is no carbon data in your example file, so DP5 has nothing to calculate, this is why the inputs to the multiprocessing function are empty. Try another example with carbon data and see if this works.
