### ISSUE TITLE
Implementation request: MOPAC as DFT program?

### ISSUE THREAD

**Issue by flatstik** [Goodman-lab/DP5#58]
Have you thought of adding support for MOPAC for performing the DFT calculations?

**Comment by HowarthA** [comment]
We are investigating some alternatives to DFT calculations, please stay tuned.

**Comment by flatstik** [comment]
Despite this enhancement proposition has been closed, I'd like to notify that [openmopac](https://github.com/openmopac/mopac) can now be found from github and so is [xtb](https://github.com/grimme-lab/xtb). The latter supports openMPI parallelization as well.
