### ISSUE TITLE
I have encountered some problems, can anyone help me?

### ISSUE THREAD

**Issue by LucasHaidar** [Goodman-lab/DP5#61]
I am trying to use the DP5 tool for my PhD project. 
I would like to know if there is a possibility to use the DP5 statistics with the data already calculated. If so, how do I enter the experimental and calculated NMR data in the program and thus manage to run DP5?

**Comment by Jonathan-Goodman** [comment]
The --AssumeDFTDone switch is useful for this. DP5 will assume that the files contain completed DFT calculations and use these instead of generating new input files
