### ISSUE TITLE
subprocess.CalledProcessError: Command '/utilities/sdconvert -isd /home/xu/Desktop/AT1_1.sdf -omae /home/xu/Desktop/AT1_1.mae' returned non-zero exit status 127.

### ISSUE THREAD

**Issue by vvvvike** [Goodman-lab/DP5#62]
settings.cfg is missing!
['/home/xu/Desktop/AT1_']
/home/xu/Desktop/NMR_folder/
NMR_path
Current working directory: /home/xu/Desktop/DP
Initial input files: ['/home/xu/Desktop/AT1_']
NMR file: [PosixPath('/home/xu/Desktop/NMR_folder/Proton'), PosixPath('/home/xu/Desktop/NMR_folder/Carbon')]
Workflow: gmns

Generating diastereomers...
Getting inchi from file  /home/xu/Desktop/AT1_.sdf
Getting inchi from file  /home/xu/Desktop/AT1_.sdf
Number of diastereomers to be generated: 2
Isomer 0 inchi = InChI=1S/C10H19NO/c1-5-9-8(4)10(12)11(9)6-7(2)3/h7-9H,5-6H2,1-4H3/t8-,9-/m0/s1/f/
Isomer 1 inchi = InChI=1S/C10H19NO/c1-5-9-8(4)10(12)11(9)6-7(2)3/h7-9H,5-6H2,1-4H3/t8-,9+/m0/s1/f/
Generated input files: ['/home/xu/Desktop/AT1_1', '/home/xu/Desktop/AT1_2']

Assuming all computations are done? ...  False
Using preexisting DFT data? ...  False
MacroModel

Setting up MacroModel files...
Could not find Schrodinger folder, please fill in PyDP4.py Settings with the path.
/bin/sh: 1: /utilities/sdconvert: not found
Traceback (most recent call last):
  File "PyDP4.py", line 841, in <module>
    main(settings)
  File "PyDP4.py", line 278, in main
    MacroModelInputs = MacroModel.SetupMacroModel(settings)
  File "/home/xu/Desktop/DP/MacroModel.py", line 60, in SetupMacroModel
    '.mae', shell=True)
  File "/home/xu/miniconda3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/xu/miniconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/utilities/sdconvert -isd /home/xu/Desktop/AT1_1.sdf -omae /home/xu/Desktop/AT1_1.mae' returned non-zero exit status 127.
——————————————————————————————
hello， I run data  downloading from https://www.repository.cam.ac.uk，but encounter some issues  as shown above , 
thank you!

**Comment by Jonathan-Goodman** [comment]
You are setting up files for MacroModel and this requires the sdconvert program which is in the $SCHRODINGER/utilities folder. The program MacroModel.py tries to set the $SCHRODINGER directory automatically. In your example, it seems to be set to "/" which is implausible. You could edit line 27 of MacroModel.py to change the default setting from '/usr/local/shared/schrodinger/current' to whatever it is on your system
